from __future__ import annotations

import fnmatch
import os
from pathlib import Path


def relpath(path: Path, root: Path) -> str:
    try:
        rel = path.resolve().relative_to(root.resolve())
    except ValueError:
        rel = path.resolve()
    return rel.as_posix()


def posix_path(value: str | Path) -> str:
    return Path(value).as_posix()


def matches_any(path: str, patterns: list[str]) -> bool:
    normalized = path.replace(os.sep, "/")
    basename = normalized.rsplit("/", 1)[-1]
    for pattern in patterns:
        pat = pattern.replace(os.sep, "/")
        if fnmatch.fnmatch(normalized, pat) or fnmatch.fnmatch(basename, pat):
            return True
        if pat.endswith("/**") and normalized.startswith(pat[:-3].rstrip("/") + "/"):
            return True
    return False


def is_test_path(path: str) -> bool:
    parts = path.split("/")
    name = parts[-1]
    return (
        "tests" in parts
        or "test" in parts
        or name.startswith("test_")
        or name.endswith("_test.py")
        or name == "conftest.py"
    )


def is_migration_path(path: str) -> bool:
    return "/migrations/" in f"/{path}" or path.startswith("migrations/")


def is_generated_like(path: str, text: str) -> bool:
    lower = text[:2048].lower()
    name = path.rsplit("/", 1)[-1].lower()
    return (
        "generated by" in lower
        or "do not edit" in lower
        or name.endswith("_pb2.py")
        or name.endswith("_pb2_grpc.py")
    )


def normalize_package_name(name: str) -> str:
    chars: list[str] = []
    previous_dash = False
    for char in name.strip().lower():
        if char.isalnum():
            chars.append(char)
            previous_dash = False
        elif char in {"-", "_", "."} and not previous_dash:
            chars.append("-")
            previous_dash = True
    return "".join(chars).strip("-")


def module_glob_match(module: str, pattern: str) -> bool:
    pat = pattern.replace("/", ".")
    return fnmatch.fnmatch(module, pat)
